# Generated by Django 4.1 on 2022-08-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
