# Generated by Django 4.0.4 on 2022-05-01 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_request_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.role'),
        ),
    ]
