# Generated by Django 4.0.4 on 2022-05-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_current_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentposition',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_position', to='api.request'),
        ),
    ]
