# Generated by Django 4.1 on 2022-08-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_faculty_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='role',
            field=models.CharField(choices=[('HD', 'HOD'), ('SA', 'Senior Advisor'), ('AR', 'Advisor'), ('TG', 'Teaching'), ('NT', 'Non Teaching')], default='TG', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
